coverage:
  status:
    patch:
      default:
        target: auto
        threshold: 5%
        base: auto
  notify:
    slack:
      clotho_build:
        url: "https://hooks.slack.com/services/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"
