coverage:
  status:
    project:
      target: 75%
      threshold: 3%
  notify:
    slack:
      clotho_build:
        url: "https://hooks.slack.com/services/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"