language: java
script:
- jdk_switcher use openjdk8
- "./gradlew build"
notifications:
  slack:
    secure: Y+XV41XKkHYXh8tF0zxsckctjer0OxeLgfy9DdK116xzf8SrTocDZH2I+6h0xWqGQ670Kk1iTi4lujRwHsu3KZ3CWpxgcYh59pfNrSsVYYtkszI5flcteNrARIlKQlbgAG6d1RR7PTa4y1Rejrj/5VyMH1ceG3LLJG3CRv9svyRF0D7TL/uh7ZxBvA3UOiw/dJhiKHIg1S6OWusPQiQZgrULMOp73+dGv2ktPicDPn/J0wncmFNpmPK1WUv+7ybWTr6eDRyZLYuZ9BNQzp+Q5qV9W55kCafOLT70FmQszXt//c6wtEWKxLozDFvTn2QeHIH6LkEX5ASLYz/hAweU4nvKxlfpfZLK/djZINYTLoIgwNbEumZwkEW3CRJtzub4CQHypKixuJQlqpOX+e5KW6pyOiRCY9H1FMzIfP4oT5TfdJlO1lxVr2nT9BKaLptCyUB1Lc9ifgqIaavJB9bYb5BywbMHXqTihAsMTPcV3CNsLw9CP2f5tBUBi61xMhyk4AoQ5zGw0S3wU8tcyeu/frCvaLu+iPCl7squVFinB27sMnMTKrme7H5rC/CDUVKX5b2HjWlwkkp45OjjkKBg3W3/j7dfxekQ6PZh99TpEbLHS6QoeVl+06MSsm5/WiZDj2gjCs2MvK7C8BZcIwx6p9OqxXfP3Cp1BDB+xqwd1EI=
after_success:
  - bash <(curl -s https://codecov.io/bash)