language: java
script:
- jdk_switcher use openjdk8
- "./gradlew clean build jacocoTestReport"
notifications:
  slack:
    secure: cp+NnTmNnKB4BGAoh7oCim5/TZFOKW6CwNzU2m2rPVqkXvzDroqAK12MytHwHBCkTQm5yDG9vMZwBS2c8VX1PQC/GacLXXL2rY9z8ezTaFzbHjd5e4TckGqzi1xPDTPNmu9Gt7p3UfjGLsP9nJaKZvlcx7NHHweBO4BKYSch9ezv7SmHL7cqQIpOEDhvnpEYYQdS+2ZTy/oqcNOe4AVazAZwoyKMCMio9gXGynChAudSGYEJhqdgqsNE+E0X3b7H4eJbqySUb49cQZwrROOv1AEG63CFIfd4vS3Piy8NwIPGiwq3C8s15PGRYye1XLHHscUnsLnntweW6/MMsQ65XtLSkOnJ8EV5vhcewgqr2ZETO7h0Yq95ah62HuOcBCPasgTgcZZe3cYP66wXMwKxs2yWLH/6a7Ik5pWyU1rbhRExFFnaeIBoio2cy2gWqUciQZLIHJTtdCRpeptmdvMZZij/SwyBM3STvqQRCAbryPToKaY72a68H4ePOaTMPpFkd0mP09XB4R1WpumJ3fReQq00gSafrvcF58in5WQ8FDKcnDAV0L6xEHy2wU5K+RPIZPHCFm4C8BYdYQweNImkhxvPmgoN7PdXX/HfQlq2Rla6/POF+gNZIbWwy7Guxv5N7n/smMNSbbnY6wa2CHIxRBhng0BOVXh4aLS73Qg819s=
after_success:
- bash <(curl -s https://codecov.io/bash)
- "./gradlew bintrayUpload"